name: Scrape and Update Map

on:
  workflow_dispatch: # Ermöglicht manuelle Auslösung

jobs:
  scrape_and_map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip uninstall -y google-cloud-language
          pip install -r requirements.txt
          python -c "import google.cloud.language; print(google.cloud.language.__version__)"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Run the scraper
        run: python scrape_faelle_2025.py

      - name: Create map
        run: python create_map.py
        env:
          GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }} # Stelle sicher, dass du auch diesen Key als Secret hast

      # Deploy to GitHub Pages (noch auskommentiert)
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
