name: Scrape and Map

on:
  schedule:
    - cron: '0 6 * * *' # Täglich um 6:00 UTC
  workflow_dispatch:

jobs:
  scrape_and_map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade google-cloud-language==2.3.0

      - name: Upgrade grpcio and protobuf
        run: |
          pip install --upgrade grpcio
          pip install --upgrade protobuf

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS }}

      - name: Run the scraper
        run: python scrape_faelle_2025.py

      - name: Create map
        run: python create_map.py
        env:
          GMAPS_API_KEY: ${{ secrets.GMAPS_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Automatisches Update: ${{ github.run_id }} – ${{ github.event_name }}"
