name: Scrape, Map, Deploy and Update JSON

on:
  schedule:
    - cron: '0 6 * * *' # Täglich um 6:00 UTC (8:00 CEST in Esbjerg im Sommer, 7:00 CEST im Winter)
  workflow_dispatch: # Ermöglicht manuelle Ausführung

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Run the scraper
        run: python scrape_faelle_2025.py

      - name: Create map
        run: python create_map.py

      - name: Git Konfiguration für Commit (JSON Update)
        run: |
          git config --local user.email "github-actions-bot@github.com"
          git config --local user.name "GitHub Actions Bot"

      - name: Commit aktualisierte JSON-Datei
        run: |
          git add public/data/faelle_2025.json
          git commit -m "Automatische Aktualisierung der faelle_2025.json" || echo "Keine Änderungen zum Committen (JSON)"

      - name: Push Änderungen zum Main-Branch (JSON Update)
        run: |
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
