name: Scrape and Update Faelle

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scrape_faelle_2025.py

      - name: Commit and push if changed using GH_PAT
         env:GH_PAT:${{ secrets.GH_PAT }}
        run: |
         git config user.name "HEALDigital12"
         git config user.email "HEALDigital12@users.noreply.github.com"
         git add public/data/faelle_2025.json
         git diff --cached --quiet || (
         git commit -m "Automatisches Update: $(date)"
         git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
         git push origin HEAD:main)
